# Makefile automatically generated by autobuild
# Also manually modified by Yang Hanlin

main.exe: HMS.o main.o
	g++ -DDBGGING $^ -o $@ -g -Wall -static-libgcc -std=c++17

HMS.o: HMS.cpp HMS.h\
       ConsoleGUI/Console.cpp ConsoleGUI/Control.cpp ConsoleGUI/Console.h ConsoleGUI/ConsoleGUI.h ConsoleGUI/Control.h\
	   Guest/Guest.cpp Guest/Guest.h\
	   Room/book.cpp Room/room.cpp Room/book.h Room/room.h\
	   User/User.cpp User/User.h\
	   Assistive/Assistive.cpp Assistive/Assistive.h\
	   VIP/vip.cpp VIP/vip.h
	g++ -DDBGGING HMS.cpp -o HMS.o -c -g -Wall -static-libgcc -std=c++17

main.o: main.cpp HMS.h
	g++ -DDBGGING main.cpp -o main.o -c -g -Wall -static-libgcc -std=c++17

.PHONY: clean
clean:
	-del *.o *.exe